title: Council Minutes
description: A public archive of council meeting notes.
baseurl: "" # leave blank unless your repo is in a subdirectory
url: "https://schi-427.github.io"

theme: minima
markdown: kramdown

# Optional: turn off future post hiding
future: true
