title: Council Minutes
description: A public archive of council meeting notes.
baseurl: "/CouncilMinutes.github.io" # this is important for project pages
url: "https://schi-427.github.io"

theme: minima
markdown: kramdown
